version: '3.1'

services:

  elasticsearch01:
    image: elasticsearch:8.7.1
    volumes:
      - type: bind
        source: ./elasticsearch.yaml
        target: /usr/share/elasticsearch/config/elasticsearch.yaml
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.authc.api_key.enabled=false
      - node.name=elasticsearch01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=example1
    ulimits:
      memlock:
        soft: -1
        hard: -1


  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
